name: Build Test with SDK

on: [push, pull_request]

env:
  PERSIST_DIR: /srv/gh-runners/quic-qrb-ros
  DL_DIR: /srv/gh-runners/quic-qrb-ros/downloads
  WORKSPACE: ${{ github.workspace }}/ros_ws
  SDK_DIR: ${{ github.workspace }}/sdk

jobs:
  set-up-sdk:
    uses: ./.github/workflows/set-up-sdk.yaml

  build:
    needs: set-up-sdk
    runs-on: [self-hosted, x86]
    timeout-minutes: 720
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ github.workspace }}/ros_ws/${{ github.event.repository.name }}

      - name: Download dependencies
        run: |
          cd ${WORKSPACE}
          # no QRB ROS dependencies
        
      - name: build
        run: |
          ls ${SDK_DIR}
          cd ${SDK_DIR}
          umask 022
          . environment-setup-armv8-2a-qcom-linux
          cd ${WORKSPACE}
          export AMENT_PREFIX_PATH="${OECORE_TARGET_SYSROOT}/usr;${OECORE_NATIVE_SYSROOT}/usr"
          export PYTHONPATH=${PYTHONPATH}:${OECORE_TARGET_SYSROOT}/usr/lib/python3.10/site-packages

          colcon build --merge-install --cmake-args \
            -DPython3_ROOT_DIR=${OECORE_TARGET_SYSROOT}/usr \
            -DPython3_NumPy_INCLUDE_DIR=${OECORE_TARGET_SYSROOT}/usr/lib/python3.10/site-packages/numpy/core/include \
            -DPYTHON_SOABI=cpython-310-aarch64-linux-gnu -DCMAKE_STAGING_PREFIX=$(pwd)/install \
            -DCMAKE_PREFIX_PATH=$(pwd)/install/share \
            -DBUILD_TESTING=OFF