name: Build Test with SDK

on: workflow_call

env:
  PERSIST_DIR: /srv/gh-runners/quic-qrb-ros
  DL_DIR: /srv/gh-runners/quic-qrb-ros/downloads
  WORKSPACE: ${{ github.workspace }}/ros_ws
  SDK_DIR: ${{ github.workspace }}/sdk

jobs:
  build:
    runs-on: [self-hosted, x86]
    timeout-minutes: 720
    steps:
      - name: Set up SDK
        run: |
          set -x
          if [ -e ${PERSIST_DIR} ] && [ -r ${PERSIST_DIR} ] && [ -x ${PERSIST_DIR} ];then
            echo "Setting up SDK..."  
            umask 022
            ${PERSIST_DIR}/sdk/qcom-robotics-ros2-humble-x86_64-qcom-robotics-full-image-armv8-2a-qcs6490-rb3gen2-vision-kit-toolchain-1.0.sh <<EOF
            ${SDK_DIR}
            Y
          EOF
          else
            echo "Downloading SDK from CLO..."
            wget -q https://artifacts.codelinaro.org/artifactory/qli-ci/flashable-binaries/qirpsdk/qcs6490-rb3gen2-vision-kit/x86/qcom-6.6.38-QLI.1.2-Ver.1.1_robotics-product-sdk-1.1.zip
            if [ $? != 0 ];then
              Download SDK failed!!!. Exit!.
              exit 2
            fi
            unzip qcom-6.6.38-QLI.1.2-Ver.1.1_robotics-product-sdk-1.1.zip
            echo "Setting up SDK..."

            umask 022
            ./target/qcs6490-rb3gen2-vision-kit/sdk/qcom-robotics-ros2-humble-x86_64-qcom-robotics-full-image-armv8-2a-qcs6490-rb3gen2-vision-kit-toolchain-1.0.sh <<EOF
            ${SDK_DIR}
            Y
          EOF
          fi